/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace BlockchainBounty {
      
    export type BountyStruct = {id: BigNumberish, creator: AddressLike, stakeAmount: BigNumberish, deadline: BigNumberish, description: string, category: BigNumberish, isActive: boolean, isClosed: boolean, totalSubmissions: BigNumberish}

    export type BountyStructOutput = [id: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint, isActive: boolean, isClosed: boolean, totalSubmissions: bigint] & {id: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint, isActive: boolean, isClosed: boolean, totalSubmissions: bigint }
  

    export type SubmissionStruct = {bountyId: BigNumberish, submitter: AddressLike, submissionLink: string, tweetLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string, projectLink: string, submissionTime: BigNumberish, isWinner: boolean, rank: BigNumberish}

    export type SubmissionStructOutput = [bountyId: bigint, submitter: string, submissionLink: string, tweetLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string, projectLink: string, submissionTime: bigint, isWinner: boolean, rank: bigint] & {bountyId: bigint, submitter: string, submissionLink: string, tweetLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string, projectLink: string, submissionTime: bigint, isWinner: boolean, rank: bigint }
  

    export type WinnerStruct = {winner: AddressLike, rank: BigNumberish, prizeAmount: BigNumberish}

    export type WinnerStructOutput = [winner: string, rank: bigint, prizeAmount: bigint] & {winner: string, rank: bigint, prizeAmount: bigint }
  
    }

  export interface BlockchainBountyInterface extends Interface {
    getFunction(nameOrSignature: "bounties" | "bountiesByCategory" | "bountyCounter" | "cancelBounty" | "createBounty" | "getActiveBountiesByCategory" | "getBountiesByCategory" | "getBounty" | "getBountyCountByCategory" | "getContractBalance" | "getSubmission" | "getSubmissionCount" | "getWinners" | "hasSubmitted" | "refundBounty" | "selectWinners" | "submissionCounters" | "submissions" | "submitWork" | "winners"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BountyCancelled" | "BountyClosed" | "BountyCreated" | "PrizeDistributed" | "WinnersSelected" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'bounties', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bountiesByCategory', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'bountyCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelBounty', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'createBounty', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveBountiesByCategory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBountiesByCategory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBounty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBountyCountByCategory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSubmission', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSubmissionCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getWinners', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasSubmitted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'refundBounty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'selectWinners', values: [BigNumberish, BigNumberish[], BigNumberish[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'submissionCounters', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submissions', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [BigNumberish, string, string, string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'winners', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'bounties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bountiesByCategory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bountyCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveBountiesByCategory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBountiesByCategory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBountyCountByCategory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubmissionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasSubmitted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundBounty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'selectWinners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissionCounters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winners', data: BytesLike): Result;
  }

  
    export namespace BountyCancelledEvent {
      export type InputTuple = [bountyId: BigNumberish, creator: AddressLike, reason: string];
      export type OutputTuple = [bountyId: bigint, creator: string, reason: string];
      export interface OutputObject {bountyId: bigint, creator: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BountyClosedEvent {
      export type InputTuple = [bountyId: BigNumberish, creator: AddressLike];
      export type OutputTuple = [bountyId: bigint, creator: string];
      export interface OutputObject {bountyId: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BountyCreatedEvent {
      export type InputTuple = [bountyId: BigNumberish, creator: AddressLike, stakeAmount: BigNumberish, deadline: BigNumberish, description: string, category: BigNumberish];
      export type OutputTuple = [bountyId: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint];
      export interface OutputObject {bountyId: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrizeDistributedEvent {
      export type InputTuple = [bountyId: BigNumberish, winner: AddressLike, rank: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [bountyId: bigint, winner: string, rank: bigint, amount: bigint];
      export interface OutputObject {bountyId: bigint, winner: string, rank: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinnersSelectedEvent {
      export type InputTuple = [bountyId: BigNumberish, winners: AddressLike[], ranks: BigNumberish[], prizeAmounts: BigNumberish[]];
      export type OutputTuple = [bountyId: bigint, winners: string[], ranks: bigint[], prizeAmounts: bigint[]];
      export interface OutputObject {bountyId: bigint, winners: string[], ranks: bigint[], prizeAmounts: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [bountyId: BigNumberish, submissionId: BigNumberish, submitter: AddressLike, submissionLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string];
      export type OutputTuple = [bountyId: bigint, submissionId: bigint, submitter: string, submissionLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string];
      export interface OutputObject {bountyId: bigint, submissionId: bigint, submitter: string, submissionLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BlockchainBounty extends BaseContract {
    
    connect(runner?: ContractRunner | null): BlockchainBounty;
    waitForDeployment(): Promise<this>;

    interface: BlockchainBountyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bounties: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, boolean, boolean, bigint] & {id: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint, isActive: boolean, isClosed: boolean, totalSubmissions: bigint }],
      'view'
    >
    

    
    bountiesByCategory: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    bountyCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelBounty: TypedContractMethod<
      [_bountyId: BigNumberish, _reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    createBounty: TypedContractMethod<
      [_description: string, _deadline: BigNumberish, _category: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getActiveBountiesByCategory: TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getBountiesByCategory: TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getBounty: TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [BlockchainBounty.BountyStructOutput],
      'view'
    >
    

    
    getBountyCountByCategory: TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getContractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getSubmission: TypedContractMethod<
      [_bountyId: BigNumberish, _submissionId: BigNumberish, ],
      [BlockchainBounty.SubmissionStructOutput],
      'view'
    >
    

    
    getSubmissionCount: TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getWinners: TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [BlockchainBounty.WinnerStructOutput[]],
      'view'
    >
    

    
    hasSubmitted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    refundBounty: TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    selectWinners: TypedContractMethod<
      [_bountyId: BigNumberish, _submissionIds: BigNumberish[], _ranks: BigNumberish[], _prizeDistribution: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    submissionCounters: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    submissions: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, string, string, string, string, string, string, string, bigint, boolean, bigint] & {bountyId: bigint, submitter: string, submissionLink: string, tweetLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string, projectLink: string, submissionTime: bigint, isWinner: boolean, rank: bigint }],
      'view'
    >
    

    
    submitWork: TypedContractMethod<
      [_bountyId: BigNumberish, _submissionLink: string, _tweetLink: string, _githubLink: string, _twitterLink: string, _videoLink: string, _indieFunLink: string, _projectLink: string, ],
      [void],
      'nonpayable'
    >
    

    
    winners: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {winner: string, rank: bigint, prizeAmount: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bounties'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, boolean, boolean, bigint] & {id: bigint, creator: string, stakeAmount: bigint, deadline: bigint, description: string, category: bigint, isActive: boolean, isClosed: boolean, totalSubmissions: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'bountiesByCategory'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bountyCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelBounty'): TypedContractMethod<
      [_bountyId: BigNumberish, _reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createBounty'): TypedContractMethod<
      [_description: string, _deadline: BigNumberish, _category: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getActiveBountiesByCategory'): TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBountiesByCategory'): TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBounty'): TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [BlockchainBounty.BountyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getBountyCountByCategory'): TypedContractMethod<
      [_category: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getContractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSubmission'): TypedContractMethod<
      [_bountyId: BigNumberish, _submissionId: BigNumberish, ],
      [BlockchainBounty.SubmissionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSubmissionCount'): TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWinners'): TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [BlockchainBounty.WinnerStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasSubmitted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refundBounty'): TypedContractMethod<
      [_bountyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'selectWinners'): TypedContractMethod<
      [_bountyId: BigNumberish, _submissionIds: BigNumberish[], _ranks: BigNumberish[], _prizeDistribution: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submissionCounters'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submissions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, string, string, string, string, string, string, string, bigint, boolean, bigint] & {bountyId: bigint, submitter: string, submissionLink: string, tweetLink: string, githubLink: string, twitterLink: string, videoLink: string, indieFunLink: string, projectLink: string, submissionTime: bigint, isWinner: boolean, rank: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [_bountyId: BigNumberish, _submissionLink: string, _tweetLink: string, _githubLink: string, _twitterLink: string, _videoLink: string, _indieFunLink: string, _projectLink: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'winners'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {winner: string, rank: bigint, prizeAmount: bigint }],
      'view'
    >;

    getEvent(key: 'BountyCancelled'): TypedContractEvent<BountyCancelledEvent.InputTuple, BountyCancelledEvent.OutputTuple, BountyCancelledEvent.OutputObject>;
getEvent(key: 'BountyClosed'): TypedContractEvent<BountyClosedEvent.InputTuple, BountyClosedEvent.OutputTuple, BountyClosedEvent.OutputObject>;
getEvent(key: 'BountyCreated'): TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
getEvent(key: 'PrizeDistributed'): TypedContractEvent<PrizeDistributedEvent.InputTuple, PrizeDistributedEvent.OutputTuple, PrizeDistributedEvent.OutputObject>;
getEvent(key: 'WinnersSelected'): TypedContractEvent<WinnersSelectedEvent.InputTuple, WinnersSelectedEvent.OutputTuple, WinnersSelectedEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'BountyCancelled(uint256,address,string)': TypedContractEvent<BountyCancelledEvent.InputTuple, BountyCancelledEvent.OutputTuple, BountyCancelledEvent.OutputObject>;
      BountyCancelled: TypedContractEvent<BountyCancelledEvent.InputTuple, BountyCancelledEvent.OutputTuple, BountyCancelledEvent.OutputObject>;
    

      'BountyClosed(uint256,address)': TypedContractEvent<BountyClosedEvent.InputTuple, BountyClosedEvent.OutputTuple, BountyClosedEvent.OutputObject>;
      BountyClosed: TypedContractEvent<BountyClosedEvent.InputTuple, BountyClosedEvent.OutputTuple, BountyClosedEvent.OutputObject>;
    

      'BountyCreated(uint256,address,uint256,uint256,string,uint8)': TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
      BountyCreated: TypedContractEvent<BountyCreatedEvent.InputTuple, BountyCreatedEvent.OutputTuple, BountyCreatedEvent.OutputObject>;
    

      'PrizeDistributed(uint256,address,uint8,uint256)': TypedContractEvent<PrizeDistributedEvent.InputTuple, PrizeDistributedEvent.OutputTuple, PrizeDistributedEvent.OutputObject>;
      PrizeDistributed: TypedContractEvent<PrizeDistributedEvent.InputTuple, PrizeDistributedEvent.OutputTuple, PrizeDistributedEvent.OutputObject>;
    

      'WinnersSelected(uint256,address[],uint8[],uint256[])': TypedContractEvent<WinnersSelectedEvent.InputTuple, WinnersSelectedEvent.OutputTuple, WinnersSelectedEvent.OutputObject>;
      WinnersSelected: TypedContractEvent<WinnersSelectedEvent.InputTuple, WinnersSelectedEvent.OutputTuple, WinnersSelectedEvent.OutputObject>;
    

      'WorkSubmitted(uint256,uint256,address,string,string,string,string,string)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }