import type { Opportunity } from "@/lib/types/opportunities";

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    type: "bounty",
    category: "content",
    title: "Write a comprehensive guide about DeFi on Solana",
    description:
      "Create an in-depth tutorial covering the basics of DeFi on Solana, including wallets, DEXs, and lending protocols.",
    organization: "Solana Foundation",
    amount: 500,
    currency: "USDC",
    deadline: new Date("2025-12-20").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["DeFi", "Solana", "Tutorial"],
    requiredSkills: ["Technical Writing", "DeFi Knowledge"],
    difficultyLevel: "intermediate",
    submissionUrl: "https://forms.gle/example",
    contactEmail: "bounties@solana.org",
    applicants: 12,
  },
  {
    id: "2",
    type: "bounty",
    category: "code",
    title: "Build a Solana NFT minting dApp",
    description:
      "Create a decentralized application that allows users to mint NFTs on Solana with a modern UI.",
    organization: "Metaplex",
    amount: 2000,
    currency: "USDC",
    deadline: new Date("2026-01-15").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["NFT", "React", "Solana"],
    requiredSkills: ["React", "Solana Web3.js", "TypeScript"],
    difficultyLevel: "advanced",
    submissionUrl: "https://github.com/metaplex",
    contactEmail: "dev@metaplex.com",
    applicants: 8,
    maxSubmissions: 5,
  },
  {
    id: "3",
    type: "bounty",
    category: "graphic-design",
    title: "Design a logo for new Web3 gaming project",
    description:
      "We need a modern, eye-catching logo that represents our blockchain gaming ecosystem.",
    organization: "StarAtlas",
    amount: 800,
    currency: "USDC",
    deadline: new Date("2025-12-15").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["Logo Design", "Gaming", "Branding"],
    requiredSkills: ["Adobe Illustrator", "Brand Design"],
    difficultyLevel: "intermediate",
    contactEmail: "design@staratlas.com",
    applicants: 23,
  },
  {
    id: "4",
    type: "job",
    jobType: "full-time",
    title: "Senior Solana Developer",
    description:
      "Join our team to build cutting-edge DeFi protocols on Solana. Work with a talented team of engineers.",
    organization: "Jupiter",
    location: "Remote",
    amount: 120000,
    currency: "USD",
    deadline: new Date("2026-02-01").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["Solana", "DeFi", "Full-time"],
    requiredSkills: ["Rust", "Solana", "Smart Contracts"],
    difficultyLevel: "expert",
    requirements: [
      "3+ years of Solana development",
      "Strong Rust skills",
      "Experience with Anchor framework",
    ],
    responsibilities: [
      "Build and maintain smart contracts",
      "Optimize protocol performance",
      "Collaborate with cross-functional teams",
    ],
    contactEmail: "careers@jup.ag",
    applicants: 45,
    salaryRange: {
      min: 120000,
      max: 180000,
    },
  },
  {
    id: "5",
    type: "project",
    duration: "medium-term",
    title: "Build a DAO governance dashboard",
    description:
      "Create a comprehensive dashboard for DAO members to view proposals, vote, and track treasury.",
    organization: "Realms",
    amount: 5000,
    currency: "USDC",
    deadline: new Date("2026-03-01").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["DAO", "Governance", "Dashboard"],
    requiredSkills: ["React", "Next.js", "Solana", "TypeScript"],
    difficultyLevel: "advanced",
    teamSize: 3,
    milestonesCount: 4,
    contactEmail: "projects@realms.today",
    applicants: 6,
    isOpenSource: true,
  },
  {
    id: "6",
    type: "bounty",
    category: "video",
    title: "Create an explainer video about Solana Mobile",
    description:
      "Produce a 3-5 minute animated explainer video showcasing the benefits of Solana Mobile.",
    organization: "Solana Mobile",
    amount: 1200,
    currency: "USDC",
    deadline: new Date("2025-12-30").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["Video", "Animation", "Mobile"],
    requiredSkills: ["Video Editing", "Animation", "Storytelling"],
    difficultyLevel: "intermediate",
    contactEmail: "marketing@solanamobile.com",
    applicants: 15,
  },
  {
    id: "7",
    type: "bounty",
    category: "ux",
    title: "Redesign wallet onboarding flow",
    description:
      "Create a user-friendly onboarding experience for new crypto wallet users.",
    organization: "Phantom",
    amount: 1500,
    currency: "USDC",
    deadline: new Date("2026-01-10").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    tags: ["UX", "Figma", "Wallet"],
    requiredSkills: ["Figma", "UX Design", "User Research"],
    difficultyLevel: "advanced",
    contactEmail: "design@phantom.app",
    applicants: 19,
  },
  {
    id: "8",
    type: "hackathon",
    title: "Solana Hyperdrive Hackathon",
    description:
      "Build the next generation of Solana applications. $100k in prizes across multiple tracks.",
    organization: "Solana Foundation",
    amount: 100000,
    currency: "USDC",
    startDate: new Date("2026-02-01").getTime(),
    endDate: new Date("2026-02-28").getTime(),
    deadline: new Date("2026-02-28").getTime(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
    status: "active",
    location: "Virtual",
    maxTeamSize: 5,
    tags: ["Hackathon", "DeFi", "NFT", "Gaming"],
    requiredSkills: ["Solana", "Rust", "TypeScript"],
    difficultyLevel: "intermediate",
    tracks: ["DeFi", "NFT", "Gaming", "Infrastructure", "Mobile"],
    prizes: [
      {
        id: "1",
        position: "1st Place",
        amount: 25000,
        description: "Grand Prize",
      },
      {
        id: "2",
        position: "2nd Place",
        amount: 15000,
        description: "Runner Up",
      },
      {
        id: "3",
        position: "3rd Place",
        amount: 10000,
        description: "Third Place",
      },
      {
        id: "4",
        position: "Best DeFi",
        amount: 10000,
        description: "Best DeFi Project",
      },
      {
        id: "5",
        position: "Best NFT",
        amount: 10000,
        description: "Best NFT Project",
      },
    ],
    contactEmail: "hackathon@solana.org",
    applicants: 234,
  },
];
